# Generated by Django 6.0.4 on 2026-09-16 15:41

import assets.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'equipment categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=120, unique=True)),
                ('internal_code', models.CharField(max_length=40, unique=True)),
                ('qr_code_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('RESERVED', 'Reservado'), ('RENTED', 'Locado'), ('MAINTENANCE', 'Em manutenção'), ('INSPECTION', 'Em inspeção'), ('INACTIVE', 'Inativo')], default='AVAILABLE', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('technical_details', models.TextField(blank=True)),
                ('current_usage_hours', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='assets.equipmentcategory')),
            ],
            options={
                'ordering': ('name', 'internal_code'),
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('PHOTO', 'Foto'), ('MANUAL', 'Manual'), ('DOCUMENT', 'Documento'), ('INSPECTION', 'Evidência de inspeção'), ('SERVICE', 'Evidência de manutenção'), ('OTHER', 'Outro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='pandora/%Y/%m/', validators=[assets.models.validate_file_size, django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp', 'doc', 'docx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='assets.equipment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
