# Generated by Django 6.0.4 on 2026-10-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcategory',
            name='pre_rental_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='return_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
