# Generated by Django 6.0.4 on 2026-10-07 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_equipmentcategory_pre_rental_checklist_and_more'),
        ('rentals', '0002_rentalquote_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='rental_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='rentals.rentalinspection'),
        ),
    ]
