# Generated by Django 6.0.4 on 2026-09-16 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventiva'), ('SCHEDULED', 'Agendada'), ('PRE_RENTAL', 'Antes da locação'), ('POST_RENTAL', 'Pós-locação')], max_length=20)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('criticality', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='assets.equipment')),
            ],
            options={
                'ordering': ('next_due_date', 'equipment__name'),
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventiva'), ('CORRECTIVE', 'Corretiva'), ('SCHEDULED', 'Agendada'), ('PRE_RENTAL', 'Antes da locação'), ('POST_RENTAL', 'Pós-locação')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('SCHEDULED', 'Agendada'), ('IN_PROGRESS', 'Em execução'), ('WAITING_PARTS', 'Aguardando peças'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=20)),
                ('priority', models.CharField(default='NORMAL', max_length=20)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('final_tests', models.TextField(blank=True)),
                ('released', models.BooleanField(default=False)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('parts_used', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='assets.equipment')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_orders', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='maintenance.maintenanceplan')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('part_used', models.CharField(blank=True, max_length=180)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='maintenance.serviceorder')),
            ],
        ),
    ]
