# Generated by Django 6.0.4 on 2026-10-07 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_service_order_workflow'),
        ('rentals', '0002_rentalquote_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='advance_notice_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='advance_notice_usage_hours',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='last_service_usage_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='rental_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order', to='rentals.rentalinspection'),
        ),
    ]
