# Generated by Django 6.0.4 on 2026-10-08 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_mediaasset_rental_inspection'),
        ('maintenance', '0003_maintenanceplan_advance_notice_days_and_more'),
        ('rentals', '0007_quote_address_complements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='plan_due_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='serviceorder',
            constraint=models.UniqueConstraint(fields=('plan', 'plan_due_date'), name='unique_service_order_plan_due_date'),
        ),
    ]
