# Generated by Django 6.0.4 on 2026-10-07 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0005_rentalquote_delivery_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7, unique=True)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('PICKUP', 'Picape'), ('VAN', 'Van'), ('TRUCK', 'Caminhão'), ('OTHER', 'Outro')], default='PICKUP', max_length=16)),
                ('capacity_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('MAINTENANCE', 'Em manutenção'), ('INACTIVE', 'Inativo')], default='AVAILABLE', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('plate',),
            },
        ),
        migrations.CreateModel(
            name='TransportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg', models.CharField(choices=[('DELIVERY', 'Entrega'), ('RETURN', 'Coleta de devolução')], max_length=10)),
                ('status', models.CharField(choices=[('PLANNED', 'A planejar'), ('IN_TRANSIT', 'Em transporte'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='PLANNED', max_length=16)),
                ('address', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transport_tasks', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driving_tasks', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_tasks', to='rentals.rentalquote')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_tasks', to='logistics.vehicle')),
            ],
            options={
                'ordering': ('scheduled_at', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('quote', 'leg'), name='unique_quote_transport_leg')],
            },
        ),
    ]
