# Generated by Django 6.0.4 on 2026-09-16 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SENT', 'Enviado'), ('APPROVED', 'Aprovado / reservado'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado')], default='DRAFT', max_length=20)),
                ('conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_quotes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_quotes', to='customers.customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_days', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition_out', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_items', to='assets.equipment')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.rentalquote')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('quote', 'equipment'), name='unique_equipment_per_quote')],
            },
        ),
    ]
