# Generated by Django 6.0.4 on 2026-10-07 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_equipmentcategory_pre_rental_checklist_and_more'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalquote',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='delivery_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='return_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalquote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('SENT', 'Enviado'), ('APPROVED', 'Aprovado / reservado'), ('ACTIVE', 'Em locação'), ('RETURNED', 'Devolvido / aguardando inspeção'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='RentalExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_end_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_extensions', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='rentals.rentalquote')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RentalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('PRE_RENTAL', 'Pré-locação'), ('RETURN', 'Devolução')], max_length=20)),
                ('result', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('APPROVED_WITH_NOTES', 'Aprovado com ressalvas'), ('BLOCKED', 'Impedido')], default='PENDING', max_length=30)),
                ('condition', models.CharField(choices=[('GOOD', 'Bom'), ('REGULAR', 'Regular'), ('DAMAGED', 'Avariado'), ('CRITICAL', 'Crítico')], default='GOOD', max_length=20)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('observations', models.TextField(blank=True)),
                ('critical_impediment', models.BooleanField(default=False)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_inspections', to='assets.equipment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_inspections', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='rentals.rentalquote')),
            ],
            options={
                'ordering': ('inspection_type', 'equipment__internal_code'),
                'constraints': [models.UniqueConstraint(fields=('quote', 'equipment', 'inspection_type'), name='unique_rental_inspection')],
            },
        ),
    ]
