# Generated by Django 6.0.4 on 2026-10-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_pre_rental_service_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalquote',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='delivery_transport_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='return_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='return_transport_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalquote',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
