# Generated by Django 6.0.4 on 2026-10-08 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RENTAL', 'Locação'), ('MAINTENANCE', 'Manutenção'), ('TRANSPORT', 'Transporte')], max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('message', models.CharField(max_length=300)),
                ('target_url', models.CharField(max_length=240)),
                ('event_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('recipient', 'event_key'), name='unique_notification_recipient_event')],
            },
        ),
    ]
